### ISSUE TITLE
Place craker-agent.jar somewhere inside .minecraft

### ISSUE THREAD

**Issue by MeeniMc** [constellation-mc/blame-log#2]
## Why 

Dropping a random .jar file in $HOME is just bad form. Confusing and even alarming if one doesn't understand where it comes from. 

## Proposition

1. Drop the craker-agent.jar file in `.minecraft/config/blame-log` or some similar place that makes sense (and links the file with the mod)
2. Rename craker-agent.jar to `instrumentation-agent.jar` or another name that is not as alarming
3. Remove the need to have an external agent altogether, but I understand from reading the code that it is technically required?

**Comment by zenfyrdev** [comment]
Hi, thanks for your concern. The file was actually supposed to be deleted after the agent was attached. Not sure what happened there. 

In the next version, it'll be in `.cracker.export/agent` of the game directory.

**Comment by zenfyrdev** [comment]
Fixed in the latest version.
